### ISSUE TITLE
remove duplicates

### ISSUE THREAD

**Issue by arnaud512** [arnaud512/worldify#18]
In the code, a lot of code is duplicate, like
`const code = localStorage.getItem('country') || 'FR';`

It would be great if there was a service that provides things like that to avoid duplication

**Comment by varunpappu** [comment]
@arnaud512  Can I pick this up?

**Comment by arnaud512** [comment]
Hey @varunpappu , I assigned you the task! Thank you! 
Happy coding!

**Comment by arnaud512** [comment]
hey @varunpappu are you working on it or can I unassign you?

**Comment by varunpappu** [comment]
Hey I am working on it and have already raised PR 😁😁 @arnaud512

**Comment by arnaud512** [comment]
Closed thanks to @varunpappu !
