### ISSUE TITLE
Active menu

### ISSUE THREAD

**Issue by arnaud512** [arnaud512/worldify#19]
For now, there is no state that indicates the current tab in the menu

![image](https://user-images.githubusercontent.com/3939593/95154301-83d51700-075f-11eb-9194-2bd8a95f63d9.png)

It could be great to see a different style for the current tab!

**Comment by sofiapatrocinio** [comment]
Hey there, do you mind assigning this task to me?

**Comment by arnaud512** [comment]
Hey @sofiapatrocinio, I assigned you the task! 
I'll check your PR this evening!
Thank you!
