### ISSUE TITLE
add currently selected country on top of switcher

### ISSUE THREAD

**Issue by arnaud512** [arnaud512/worldify#27]
When you select a country, it could be great if the selected country goes to the first position with a selected state background
For now, nothing is displayed, only a hover
![image](https://user-images.githubusercontent.com/3939593/95242702-8d04c900-07dd-11eb-9240-72ae219631b9.png)

**Comment by PBWim** [comment]
@arnaud512 
I have added a pull request (#34) to log the files.
Please review the pull request and provide feedback.
Thank you...

```hacktoberfest-2020```
